text1 = input()
print ("The given text:",text1)
print ("# of a:",text1.count('a'))
print ("# of b:",text1.count('b'))
print ("# of c:",text1.count('c'))
print ("# of d:",text1.count('d'))
print ("# of e:",text1.count('e'))